### ISSUE TITLE
Few additional asks in terms of the prometheus blog

### ISSUE THREAD

**Issue by krmahadevan** [PierreVincent/pierrevincent.github.io#1]
@PierreVincent - The blog from this repository quickly gave me the much needed overview I was hoping to get. So thanks for that.

Here are a couple of things that I was hoping you could help with (either as a reply on this issue itself or by adding an elaborate post itself)

* How does one decide if one should go for a `push` model powered by the push gateway (or) the `pull` model ? Whatever I have seen on the internet seems to be a bit vague.

Here's my specific use case. I am trying to build a standalone tool which would serve as a load generator and also emits metrics for my tracking needs. The load generator could run anywhere from a few minutes to a few hours. I am having a tough time trying to decide if I should emit metrics on the `/metrics` (pull model) (or) just use the push model. My tool is not a service, but its also not a batch job. What are the dos and don's that I should be vary of, if I choose push (or) pull model for my use case.

* I still haven't been able to figure out properly as to when does one use a histogram (or) a summary. Would you be able to help out with some really elaborate practical examples which can help anyone understand the meaning of these two metric types and how to decide which to use when ?

**Comment by PierreVincent** [comment]
Thanks Kirshnan, glad the blog series was helpful to you.

I can give a quick reply to your questions, and as I have been asked similar ones, I will try to elaborate the answers in a post in the next week or so!

> How does one decide if one should go for a push model powered by the push gateway (or) the pull model ? Whatever I have seen on the internet seems to be a bit vague.

Rule of thumb is: use `pull` for everything, unless the metrics are coming from ad-hoc tasks, which aren't running continuously (and potentially harder to target via service discovery). In your particular example, even though you are not considering your tool as a batch job, it sounds to me like `push` is the way to go because your load generator is not a long-running service.

> I still haven't been able to figure out properly as to when does one use a histogram (or) a summary. Would you be able to help out with some really elaborate practical examples which can help anyone understand the meaning of these two metric types and how to decide which to use when ?

Histogram and Summary are basically used for the same thing: data distribution - they only differ by where the quantiles calculations happen:

- Histograms only store observation buckets on the client side, and quantiles are calculated at query time (`histogram_quantile` Prometheus function)
- Summaries do the quantile calculations on the client side and expose them directly as metrics

Quantile calculations are expensive, so depending on the type of activity or queries, you can use either of them. Histograms push the heavy work to Prometheus itself, while Summaries keep this work at the instrumentation level (in your own services).

The [part 2](https://pierrevincent.github.io/2017/12/prometheus-blog-series-part-2-metric-types/) of the series goes into more detail about why you would use Histograms/Summaries rather than Counters. In short: counters only give you averages, which hide data distribution. If you're monitoring latency, a metric like `average response time` doesn't tell you much; Histograms give you the ability to have metrics like `99% of requests respond within __` or `%age of requests responding within 250ms` (which are much more indicative of your service performance/reliability).

**Comment by krmahadevan** [comment]
@PierreVincent

My apologies for getting back on this late and thank you so much for all
the answers that you have shared.

> In your particular example, even though you are not considering your tool
as a batch job, it sounds to me like push is the way to go because your
load generator is not a long-running service.

From what I read about pushgateways, it looks like I have to also manage
flushing out the stale metrics from the pushgateways else it seems it stays
there for eternity.  Quoting the documentation from [here](
https://prometheus.io/docs/practices/pushing/#should-i-be-using-the-pushgateway
)

> The Pushgateway never forgets series pushed to it and will expose them to
Prometheus forever unless those series are manually deleted via the
Pushgateway's API.

I didnt want to do this because this would mean that I would need to add
extra code into my standalone application which will take care of doing
this before it does anything else (Or is my understanding wrong)

Histograms Vs Summary

One of my colleague had this as an explanation for histogram and summary...

Histogram <-- Use histogram when you know the bucket values exactly
Summary <-- Use summary when you dont know exactly what your bucket values
are.

Is that a valid explanation? I am still a bit lost (Yes I re-read the part
2 series from your blog) when it comes to histograms  and summary.

So apart from where the calculation happens

* Histograms - calculations happen at the prometheus server
* Summary - calculations happen at the client

are there no other differences between the two and they can be used
interchangeably is it ?

**Comment by PierreVincent** [comment]
Regarding the push gateway, it has definitely drawbacks... like data hanging around forever, and it being a single point of failure.
In your example, if you are pushing the same metrics, I believe they will overwrite the previous ones (it depends on how you use the API to push your metrics) so the deletion of metrics at the start of a run might not be something you need to deal with.

Your colleague makes a good point about the buckets. Essentially, Histograms are a much cheaper overall, because they rely on bucket aggregation (but like any aggregation it means losing data/precision)... so if you know the buckets (e.g. what kind of latency profile you expect), then Histograms are a better choice. If the data variates so much that buckets cannot be easily defined, then Summaries can help.

Keep in mind that Summaries are typically not aggregatable, so if you have multiple instances exposing the same summary metric, you can't get a global summary (average it is meaningless). Histograms allow aggregation through the prometheus functions. 

In my own experience I have always been using Histograms to measure distribution.

The documentations provides a good breakdown of the differences between the two: https://prometheus.io/docs/practices/histograms/#quantiles
